languageCode = "en"
languageName = "English"
weight = 1
title = "Lia's Blog"

[params]
displayName = "EN"
isoCode = "en"
rtl = false
dateFormat = "January 2nd, 2006"

[params.author]
name = "Lia Milenakos"
image = "milenakos.png"
headline = "meow"
bio = "Hi! I'm a silly catgirl who makes Discord bots and other random nonsense!"
links = [
    { email = "mailto:lia@minkos.lol" },
    { link = "https://minkos.lol/" },
    { discord = "https://discord.gg/staring" },
    { github = "https://github.com/milenakos" }
]
